In [16]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [29]:
df = pd.read_csv("ordinal.csv")

In [18]:
df.head()

   Id  Education Country
0   1        PhD     USA
1   2    Masters      UK
2   3  Bachelors  Canada
3   4        PhD     USA
4   5    Masters     USA

In [19]:
df["Education"].unique()

array(['PhD', 'Masters', 'Bachelors'], dtype=object)

In [20]:
df["Education"].value_counts()

PhD          100
Bachelors    100
Masters      100
Name: Education, dtype: int64

In [21]:
df["Country"].value_counts()

Canada    120
USA        90
UK         90
Name: Country, dtype: int64

In [24]:
enc = OrdinalEncoder()
enc.fit_transform(df[["Education"]])

array([[2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.]])

In [25]:
df[["Education"]] = enc.fit_transform(df[["Education"]])

In [26]:
df.head()

   Id  Education Country
0   1        2.0     USA
1   2        1.0      UK
2   3        0.0  Canada
3   4        2.0     USA
4   5        1.0     USA

In [27]:
edu = ['PhD', 'Masters', 'Bachelors']

In [30]:
enc = OrdinalEncoder(categories=[edu])
enc.fit_transform(df[["Education"]])

array([[0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.]])

In [31]:
df[["Education"]] = enc.fit_transform(df[["Education"]])

In [32]:
df.head()

   Id  Education Country
0   1        0.0     USA
1   2        1.0      UK
2   3        2.0  Canada
3   4        0.0     USA
4   5        1.0     USA